name: Build Windows Portable EXE (Tauri)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app (no installer, portable exe)
        run: npx tauri build --bundles none

      - name: Upload portable exe
        uses: actions/upload-artifact@v4
        with:
          name: pulse-windows-portable
          path: |
            src-tauri/target/release/*.exe
            src-tauri/target/release/*.dll
            src-tauri/target/release/*.pak
            src-tauri/target/release/resources/**
          if-no-files-found: error
